server:
  port: 8080
  ip: ${CUSTOM_SERVER_IP:localhost}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: security-service
        url: /security-swagger/v3/api-docs
      - name: data-service
        url: /data-swagger/v3/api-docs

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway-Service, EgorS-Gateway
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security-swagger/**, /auth/**
        - id: data-service
          uri: lb://data-service
          predicates:
            - Path=/data-swagger/**, /post-questionnaires/**, /diagnostic-sheets/**, /pre-questionnaires/**, /api/**, /management/**, /diagram-detail-changes/**
          filters:
            - AddRequestHeader=GatewayIP,${CUSTOM_SERVER_IP:localhost}
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

secret-api:
  key: SuperSecretApiWord

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.254.10:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
