spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ietecproject@gmail.com
    password: pdpsapywgohwwcrt
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.254.10:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true